services:
  app:
    build: .
    volumes:
      - .:/code
    ports:
      - 8000:8000
    image: app:code
    container_name: note_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    container_name: note_app_db

volumes:
  pg_data:
    driver: local