"""edit category

Revision ID: 1298a510c93b
Revises: 6840b62ec908
Create Date: 2024-07-19 23:14:13.696994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1298a510c93b'
down_revision: Union[str, None] = '6840b62ec908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('notes_id', sa.Integer(), nullable=True))
    op.add_column('categories', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'categories', 'notes', ['notes_id'], ['id'])
    op.create_foreign_key(None, 'categories', 'users', ['user_id'], ['id'])
    op.drop_constraint('notes_category_id_fkey', 'notes', type_='foreignkey')
    op.drop_column('notes', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('notes_category_id_fkey', 'notes', 'categories', ['category_id'], ['id'])
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'user_id')
    op.drop_column('categories', 'notes_id')
    # ### end Alembic commands ###
