"""title colum

Revision ID: 7f29086ed0b0
Revises: 857be8406ab7
Create Date: 2024-07-17 18:46:59.522774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f29086ed0b0'
down_revision: Union[str, None] = '857be8406ab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notes_title', table_name='notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_notes_title', 'notes', ['title'], unique=False)
    # ### end Alembic commands ###
